apiVersion: v1
kind: Secret
metadata:
  name: big-secret
  namespace: cesar
data:
  password: YWJjMTIz
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: telequark
  name: telequark
  namespace: cesar
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: telequark
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: telequark
    spec:
      containers:
      - env:
        - name: foo
          value: bar
        - name: one-big-secret
          valueFrom:
            secretKeyRef:
              name: big-secret
              key: password
        image: cesartl/telequark
        imagePullPolicy: Always
        name: telequark
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-04-07T16:00:48Z"
    lastUpdateTime: "2019-04-27T11:18:04Z"
    message: ReplicaSet "telequark-b5cf47895" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-04-27T11:20:31Z"
    lastUpdateTime: "2019-04-27T11:20:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 16
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
